#! /usr/bin/env python3

from binance_api import rest_master

rest_api = rest_master.Binance_REST(public_key='', private_key='')

# Rest endpoints to test:
def test_rest():
	print('Testing... [get_blvt_info]')
	rest_api.get_blvt_info(IS_TEST=True)
	print('Testing... [subscribe_blvt]')
	rest_api.subscribe_blvt(IS_TEST=True)
	print('Testing... [query_subscription_record]')
	rest_api.query_subscription_record(IS_TEST=True)
	print('Testing... [redeem_blvt]')
	rest_api.redeem_blvt(IS_TEST=True)
	print('Testing... [query_redemption_record]')
	rest_api.query_redemption_record(IS_TEST=True)
	print('Testing... [get_blvt_userLimit]')
	rest_api.get_blvt_userLimit(IS_TEST=True)
	print('Testing... [get_swap_pools]')
	rest_api.get_swap_pools()
	print('Testing... [get_liquidity_poolInfo]')
	rest_api.get_liquidity_poolInfo(IS_TEST=True)
	print('Testing... [add_liquidity]')
	rest_api.add_liquidity(IS_TEST=True)
	print('Testing... [remove_liquidity]')
	rest_api.remove_liquidity(IS_TEST=True)
	print('Testing... [get_liquidity_record]')
	rest_api.get_liquidity_record(IS_TEST=True)
	print('Testing... [get_quote]')
	rest_api.get_quote(IS_TEST=True)
	print('Testing... [make_swap]')
	rest_api.make_swap(IS_TEST=True)
	print('Testing... [get_swap_history]')
	rest_api.get_swap_history(IS_TEST=True)
	print('Testing... [futures_transfer]')
	rest_api.futures_transfer(IS_TEST=True)
	print('Testing... [get_futures_transactions]')
	rest_api.get_futures_transactions(IS_TEST=True)
	print('Testing... [borrow_crossCollat]')
	rest_api.borrow_crossCollat(IS_TEST=True)
	print('Testing... [get_crossCollat_borrowHist]')
	rest_api.get_crossCollat_borrowHist(IS_TEST=True)
	print('Testing... [repay_crossCollat]')
	rest_api.repay_crossCollat(IS_TEST=True)
	print('Testing... [get_crossCollat_repayHist]')
	rest_api.get_crossCollat_repayHist(IS_TEST=True)
	print('Testing... [get_crossCollat_wallet]')
	rest_api.get_crossCollat_wallet()
	print('Testing... [get_crossCollat_wallet_v2]')
	rest_api.get_crossCollat_wallet_v2()
	print('Testing... [get_crossCollat_info]')
	rest_api.get_crossCollat_info(IS_TEST=True)
	print('Testing... [get_crossCollat_info_v2]')
	rest_api.get_crossCollat_info_v2(IS_TEST=True)
	print('Testing... [get_crossCollat_rate_LTV]')
	rest_api.get_crossCollat_rate_LTV(IS_TEST=True)
	print('Testing... [get_crossCollat_rate_LTV_v2]')
	rest_api.get_crossCollat_rate_LTV_v2(IS_TEST=True)
	print('Testing... [get_crossCollat_max_LTV]')
	rest_api.get_crossCollat_max_LTV(IS_TEST=True)
	print('Testing... [get_crossCollat_max_LTV_v2]')
	rest_api.get_crossCollat_max_LTV_v2(IS_TEST=True)
	print('Testing... [adjust_crossCollat_LTV]')
	rest_api.adjust_crossCollat_LTV(IS_TEST=True)
	print('Testing... [adjust_crossCollat_LTV_v2]')
	rest_api.adjust_crossCollat_LTV_v2(IS_TEST=True)
	print('Testing... [adjust_crossCollat_LTV_history]')
	rest_api.adjust_crossCollat_LTV_history(IS_TEST=True)
	print('Testing... [adjust_crossCollat_liquidation_history]')
	rest_api.adjust_crossCollat_liquidation_history(IS_TEST=True)
	print('Testing... [get_collatRepay_limit]')
	rest_api.get_collatRepay_limit(IS_TEST=True)
	print('Testing... [get_collatRepay_quote]')
	rest_api.get_collatRepay_quote(IS_TEST=True)
	print('Testing... [collateral_repay]')
	rest_api.collateral_repay(IS_TEST=True)
	print('Testing... [get_collatRepay_result]')
	rest_api.get_collatRepay_result(IS_TEST=True)
	print('Testing... [get_crossCollat_interestHist]')
	rest_api.get_crossCollat_interestHist(IS_TEST=True)
	print('Testing... [margin_transfer]')
	rest_api.margin_transfer(IS_TEST=True)
	print('Testing... [margin_accountBorrow]')
	rest_api.margin_accountBorrow(IS_TEST=True)
	print('Testing... [margin_accountRepay]')
	rest_api.margin_accountRepay(IS_TEST=True)
	print('Testing... [query_margin_asset]')
	rest_api.query_margin_asset(IS_TEST=True)
	print('Testing... [query_crossPair]')
	rest_api.query_crossPair(IS_TEST=True)
	print('Testing... [get_margin_allAssets]')
	rest_api.get_margin_allAssets()
	print('Testing... [get_allCrossPairs]')
	rest_api.get_allCrossPairs()
	print('Testing... [query_margin_priceIndex]')
	rest_api.query_margin_priceIndex(IS_TEST=True)
	print('Testing... [get_margin_crossTransferHistory]')
	rest_api.get_margin_crossTransferHistory(IS_TEST=True)
	print('Testing... [get_loanRecord]')
	rest_api.get_loanRecord(IS_TEST=True)
	print('Testing... [get_repayRecord]')
	rest_api.get_repayRecord(IS_TEST=True)
	print('Testing... [get_interestHistory]')
	rest_api.get_interestHistory(IS_TEST=True)
	print('Testing... [get_fLiquidationRecord]')
	rest_api.get_fLiquidationRecord(IS_TEST=True)
	print('Testing... [get_cross_accountDetails]')
	rest_api.get_cross_accountDetails()
	print('Testing... [get_maxBorrow]')
	rest_api.get_maxBorrow(IS_TEST=True)
	print('Testing... [get_maxOutAmmount]')
	rest_api.get_maxOutAmmount(IS_TEST=True)
	print('Testing... [create_isolatedMaringAccount]')
	rest_api.create_isolatedMaringAccount(IS_TEST=True)
	print('Testing... [isolated_transfer]')
	rest_api.isolated_transfer(IS_TEST=True)
	print('Testing... [get_isolated_transferHistory]')
	rest_api.get_isolated_transferHistory(IS_TEST=True)
	print('Testing... [get_isolated_accountInfo]')
	rest_api.get_isolated_accountInfo(IS_TEST=True)
	print('Testing... [get_isolated_symbol]')
	rest_api.get_isolated_symbol(IS_TEST=True)
	print('Testing... [get_isolated_symbol_all]')
	rest_api.get_isolated_symbol_all()
	print('Testing... [toggle_BNB_burn_ST_MI]')
	rest_api.toggle_BNB_burn_ST_MI(IS_TEST=True)
	print('Testing... [get_BNB_burn_status]')
	rest_api.get_BNB_burn_status()
	print('Testing... [test_ping]')
	rest_api.test_ping()
	print('Testing... [get_serverTime]')
	rest_api.get_serverTime()
	print('Testing... [get_ExchangeInfo]')
	rest_api.get_ExchangeInfo()
	print('Testing... [get_orderBook]')
	rest_api.get_orderBook(IS_TEST=True)
	print('Testing... [get_aggTradeList]')
	rest_api.get_aggTradeList(IS_TEST=True)
	print('Testing... [get_averagePrice]')
	rest_api.get_averagePrice(IS_TEST=True)
	print('Testing... [get_24hTicker]')
	rest_api.get_24hTicker(IS_TEST=True)
	print('Testing... [get_priceTicker]')
	rest_api.get_priceTicker(IS_TEST=True)
	print('Testing... [get_orderbookTicker]')
	rest_api.get_orderbookTicker(IS_TEST=True)
	print('Testing... [get_algorithm]')
	rest_api.get_algorithm()
	print('Testing... [get_coinNames]')
	rest_api.get_coinNames()
	print('Testing... [get_minerList_detail]')
	rest_api.get_minerList_detail(IS_TEST=True)
	print('Testing... [get_minerList]')
	rest_api.get_minerList(IS_TEST=True)
	print('Testing... [get_earningsList]')
	rest_api.get_earningsList(IS_TEST=True)
	print('Testing... [get_extraBonusList]')
	rest_api.get_extraBonusList(IS_TEST=True)
	print('Testing... [get_hashrateResaleList]')
	rest_api.get_hashrateResaleList(IS_TEST=True)
	print('Testing... [get_hashrateResaleDetail]')
	rest_api.get_hashrateResaleDetail(IS_TEST=True)
	print('Testing... [post_hashrateResale]')
	rest_api.post_hashrateResale(IS_TEST=True)
	print('Testing... [cancel_hashrateResale]')
	rest_api.cancel_hashrateResale(IS_TEST=True)
	print('Testing... [get_statisticList]')
	rest_api.get_statisticList(IS_TEST=True)
	print('Testing... [get_accountList]')
	rest_api.get_accountList(IS_TEST=True)
	print('Testing... [get_productList]')
	rest_api.get_productList(IS_TEST=True)
	print('Testing... [get_dailyPurchaseQuota]')
	rest_api.get_dailyPurchaseQuota(IS_TEST=True)
	print('Testing... [purchase_product]')
	rest_api.purchase_product(IS_TEST=True)
	print('Testing... [get_dailyRedemptionQuota]')
	rest_api.get_dailyRedemptionQuota(IS_TEST=True)
	print('Testing... [redeem_product]')
	rest_api.redeem_product(IS_TEST=True)
	print('Testing... [get_product_position]')
	rest_api.get_product_position(IS_TEST=True)
	print('Testing... [get_FnAProject_list]')
	rest_api.get_FnAProject_list(IS_TEST=True)
	print('Testing... [purchase_FnAProject]')
	rest_api.purchase_FnAProject(IS_TEST=True)
	print('Testing... [get_FnAProject_position]')
	rest_api.get_FnAProject_position(IS_TEST=True)
	print('Testing... [get_lending]')
	rest_api.get_lending()
	print('Testing... [get_purchase_record]')
	rest_api.get_purchase_record(IS_TEST=True)
	print('Testing... [get_redemption_record]')
	rest_api.get_redemption_record(IS_TEST=True)
	print('Testing... [get_interest_history]')
	rest_api.get_interest_history(IS_TEST=True)
	print('Testing... [change_position]')
	rest_api.change_position(IS_TEST=True)
	print('Testing... [place_order_test]')
	rest_api.place_order_test(IS_TEST=True)
	print('Testing... [place_order_oco]')
	rest_api.place_order_oco(IS_TEST=True)
	print('Testing... [cancel_order_oco]')
	rest_api.cancel_order_oco(IS_TEST=True)
	print('Testing... [query_order_oco]')
	rest_api.query_order_oco(IS_TEST=True)
	print('Testing... [get_all_orders_oco]')
	rest_api.get_all_orders_oco(IS_TEST=True)
	print('Testing... [get_open_orders_oco]')
	rest_api.get_open_orders_oco()
	print('Testing... [get_accountInfo]')
	rest_api.get_accountInfo()
	print('Testing... [get_subAccount_list]')
	rest_api.get_subAccount_list(IS_TEST=True)
	print('Testing... [get_subAccount_spotTransferHistory_wapi]')
	rest_api.get_subAccount_spotTransferHistory_wapi(IS_TEST=True)
	print('Testing... [get_subAccount_spotTransferHistory_sapi]')
	rest_api.get_subAccount_spotTransferHistory_sapi(IS_TEST=True)
	print('Testing... [subAccount_spotAsset_transfer]')
	rest_api.subAccount_spotAsset_transfer(IS_TEST=True)
	print('Testing... [get_subAccount_futuresTransferHistory]')
	rest_api.get_subAccount_futuresTransferHistory(IS_TEST=True)
	print('Testing... [subAccount_futuresAsset_transfer]')
	rest_api.subAccount_futuresAsset_transfer(IS_TEST=True)
	print('Testing... [get_subAccount_assets]')
	rest_api.get_subAccount_assets(IS_TEST=True)
	print('Testing... [get_subAccount_spotAssetsSummary]')
	rest_api.get_subAccount_spotAssetsSummary(IS_TEST=True)
	print('Testing... [get_subAccount_depositAddress]')
	rest_api.get_subAccount_depositAddress(IS_TEST=True)
	print('Testing... [get_subAccount_depositHistory]')
	rest_api.get_subAccount_depositHistory(IS_TEST=True)
	print('Testing... [get_subAccount_statusFnM]')
	rest_api.get_subAccount_statusFnM(IS_TEST=True)
	print('Testing... [enable_subAccount_margin]')
	rest_api.enable_subAccount_margin(IS_TEST=True)
	print('Testing... [get_subAccount_marginAccount]')
	rest_api.get_subAccount_marginAccount(IS_TEST=True)
	print('Testing... [get_subAccount_marginAccountSummary]')
	rest_api.get_subAccount_marginAccountSummary()
	print('Testing... [enable_subAccount_futures]')
	rest_api.enable_subAccount_futures(IS_TEST=True)
	print('Testing... [get_subAccount_futuresAccount]')
	rest_api.get_subAccount_futuresAccount(IS_TEST=True)
	print('Testing... [get_subAccount_futuresAccountSummary]')
	rest_api.get_subAccount_futuresAccountSummary()
	print('Testing... [get_subAccount_positionRisk]')
	rest_api.get_subAccount_positionRisk(IS_TEST=True)
	print('Testing... [subAccount_futures_transfer]')
	rest_api.subAccount_futures_transfer(IS_TEST=True)
	print('Testing... [subAccount_margin_transfer]')
	rest_api.subAccount_margin_transfer(IS_TEST=True)
	print('Testing... [master_sub_transfer]')
	rest_api.master_sub_transfer(IS_TEST=True)
	print('Testing... [sub_master_transfer]')
	rest_api.sub_master_transfer(IS_TEST=True)
	print('Testing... [get_subAccount_transferHistory]')
	rest_api.get_subAccount_transferHistory(IS_TEST=True)
	print('Testing... [make_universalTransfer]')
	rest_api.make_universalTransfer(IS_TEST=True)
	print('Testing... [get_universalTransferHisotry]')
	rest_api.get_universalTransferHisotry(IS_TEST=True)
	print('Testing... [get_subAccount_futuresAccount_v2]')
	rest_api.get_subAccount_futuresAccount_v2(IS_TEST=True)
	print('Testing... [get_subAccount_futuresAccountSummary_v2]')
	rest_api.get_subAccount_futuresAccountSummary_v2(IS_TEST=True)
	print('Testing... [get_subAccount_positionRisk_v2]')
	rest_api.get_subAccount_positionRisk_v2(IS_TEST=True)
	print('Testing... [get_systemStatus]')
	rest_api.get_systemStatus()
	print('Testing... [get_allCoinsInfo]')
	rest_api.get_allCoinsInfo()
	print('Testing... [get_dailySnapshot]')
	rest_api.get_dailySnapshot(IS_TEST=True)
	print('Testing... [disable_withdrawSwitch]')
	rest_api.disable_withdrawSwitch()
	print('Testing... [enable_withdrawSwitch]')
	rest_api.enable_withdrawSwitch()
	print('Testing... [make_withdraw_SAPI]')
	rest_api.make_withdraw_SAPI(IS_TEST=True)
	print('Testing... [make_withdraw]')
	rest_api.make_withdraw(IS_TEST=True)
	print('Testing... [get_depositHistory_SN]')
	rest_api.get_depositHistory_SN(IS_TEST=True)
	print('Testing... [get_depositHistory]')
	rest_api.get_depositHistory(IS_TEST=True)
	print('Testing... [get_withdrawHistory_SN]')
	rest_api.get_withdrawHistory_SN(IS_TEST=True)
	print('Testing... [get_withdrawHistory]')
	rest_api.get_withdrawHistory(IS_TEST=True)
	print('Testing... [depositAddress_SN]')
	rest_api.depositAddress_SN(IS_TEST=True)
	print('Testing... [depositAddress]')
	rest_api.depositAddress(IS_TEST=True)
	print('Testing... [get_accountStatus]')
	rest_api.get_accountStatus()
	print('Testing... [get_apiStatus]')
	rest_api.get_apiStatus()
	print('Testing... [get_dustLog]')
	rest_api.get_dustLog()
	print('Testing... [make_dustTransfer]')
	rest_api.make_dustTransfer(IS_TEST=True)
	print('Testing... [get_dividendRecord]')
	rest_api.get_dividendRecord(IS_TEST=True)
	print('Testing... [get_assetDetail]')
	rest_api.get_assetDetail()
	print('Testing... [get_tradeFee]')
	rest_api.get_tradeFee(IS_TEST=True)
	print('Testing... [make_universalTransfer]')
	rest_api.make_universalTransfer(IS_TEST=True)
	print('Testing... [get_universalTransferHistory]')
	rest_api.get_universalTransferHistory(IS_TEST=True)
	print('Testing... [get_account]')
	rest_api.get_account()
	print('Testing... [place_order]')
	rest_api.place_order(IS_TEST=True)
	print('Testing... [get_order]')
	rest_api.get_order(IS_TEST=True)
	print('Testing... [cancel_order]')
	rest_api.cancel_order(IS_TEST=True)
	print('Testing... [cancel_all_orders]')
	rest_api.cancel_all_orders(IS_TEST=True)
	print('Testing... [get_all_orders]')
	rest_api.get_all_orders(IS_TEST=True)
	print('Testing... [get_all_trades]')
	rest_api.get_all_trades(IS_TEST=True)
	print('Testing... [get_open_orders]')
	rest_api.get_open_orders(IS_TEST=True)

test_rest()